# fly.toml app configuration file generated for photonet on 2023-08-02T01:14:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "photonet"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
[env]
  DB_USER="rlzmgwjt"
  DB_PASSWORD="2kpcXGpyPkhlEay6bZ5gsyoXdV9miRnh"
  DB_DOMAIN="otto.db.elephantsql.com"
  DB_NAME="rlzmgwjt"
  DB_PORT=5432

  SQLALCHEMY_DATABASE_URL="postgresql+psycopg2://rlzmgwjt:2kpcXGpyPkhlEay6bZ5gsyoXdV9miRnh@otto.db.elephantsql.com:5432/rlzmgwjt"

  jwt_secret_key="secret"
  jwt_algorithm="HS256"

  MAIL_USERNAME="photonet-web11@meta.ua"
  MAIL_FROM="photonet-web11@meta.ua"
  MAIL_PASSWORD="Goit_test2023"
  MAIL_PORT=465
  MAIL_SERVER="smtp.meta.ua"

  redis_host="195.201.150.230"
  redis_port=6379
  cloudinary_name="dhvlor48m"
  cloudinary_api_key=151969746965845
  cloudinary_api_secret="Fm-W7tBFKjj9KY2BDxI7S3mfeEM"

